### ISSUE TITLE
ImportError: No module named 'nbformat'

### ISSUE THREAD

**Issue by nmtoken** [Diuke/GeoPriv#10]
When trying to install the plugin get error:

    2019-05-20T17:59:18     WARNING    Traceback (most recent call last):
                  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in startPlugin
                  plugins[packageName] = package.classFactory(iface)
                  File "/home/XXXX/.local/share/QGIS/QGIS3/profiles/YYYY/python/plugins/GeoPriv/__init__.py", line 9, in classFactory
                  from .geoprivacy import Geopriv
                  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
                  mod = _builtin_import(name, globals, locals, fromlist, level)
                  File "/home/XXXX/.local/share/QGIS/QGIS3/profiles/YYYY/python/plugins/GeoPriv/geoprivacy.py", line 42, in 
                  from nbformat.sign import algorithms
                  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
                  mod = _builtin_import(name, globals, locals, fromlist, level)
                  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
                  mod = _builtin_import(name, globals, locals, fromlist, level)
                 ImportError: No module named 'nbformat'

**Comment by Diuke** [comment]
I found the bug, apparently, Eclipse auto-imported the library because we wrote "algorithm" somewhere in the code.
Working on a fix will be available on next version, sorry for the inconvenient.
Although, the fix has already been applied to this repository, so feel free to download it and use it (to import the plugin from the folder you have to change the name to "GeoPriv-master" to only "GeoPriv")
