### ISSUE TITLE
ModuleNotFoundError: No module named 'geoprivacy' on installation

### ISSUE THREAD

**Issue by mstuyts** [Diuke/GeoPriv#9]
When I install the plugin in QGIS 3.6.2 on Windows 10, I get the following error:

```
Couldn't load plugin 'GeoPriv' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'geoprivacy' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/myname/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoPriv\__init__.py", line 9, in classFactory
    from .geoprivacy import Geopriv
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/myname/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoPriv\geoprivacy.py", line 37, in 
    from .LPPMs.spatial.Spatial import Spatial
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/myname/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoPriv\LPPMs\spatial\Spatial.py", line 6, in 
    from geoprivacy.utils.DataModel import DataModel
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'geoprivacy'
```

**Comment by Diuke** [comment]
Apparently, when I was testing the plugin the folder name was 'geoprivacy' but had to rename the folder to 'GeoPriv' so some imports were broken.

The last commit fixes this issue and the plugin was uploaded again to QGIS for approval.

Thank you very much.

**Comment by mstuyts** [comment]
Thanks for the quick fix.

Next time you fix a bug you better change the version number. I didn't uninstall the plugin when I got the error before.  This means that now QGIS didn't give me a notification of the new version of the plugin, because you didn't change the version number and QGIS thinks it's still the same version.  If it's a minor bugfix you could have called it version 1.0.1.

**Comment by Diuke** [comment]
Thank you very much Michel, next time sure I will.
